/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {},
  },
  plugins: [require("@tailwindcss/typography"), require("daisyui")],
  daisyui: {
    themes: [
      {
        hcoco: {
          primary: "#0f766e",
          "primary-content": "#ecfeff",
          secondary: "#2563eb",
          "secondary-content": "#eff6ff",
          accent: "#d97706",
          "accent-content": "#fff7ed",
          neutral: "#14213d",
          "neutral-content": "#f8fafc",
          "base-100": "#f8fafc",
          "base-200": "#eef3f7",
          "base-300": "#dbe5ee",
          "base-content": "#14213d",
          info: "#0284c7",
          "info-content": "#f0f9ff",
          success: "#15803d",
          "success-content": "#f0fdf4",
          warning: "#d97706",
          "warning-content": "#fff7ed",
          error: "#dc2626",
          "error-content": "#fef2f2",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.375rem",
          "--rounded-badge": "999px",
          "--animation-btn": "0.16s",
          "--animation-input": "0.16s",
          "--btn-focus-scale": "0.98",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.375rem",
        },
      },
      {
        "hcoco-dark": {
          primary: "#2dd4bf",
          "primary-content": "#042f2e",
          secondary: "#93c5fd",
          "secondary-content": "#172554",
          accent: "#fbbf24",
          "accent-content": "#451a03",
          neutral: "#e2e8f0",
          "neutral-content": "#0f172a",
          "base-100": "#0f172a",
          "base-200": "#111827",
          "base-300": "#1f2937",
          "base-content": "#e5edf6",
          info: "#38bdf8",
          "info-content": "#082f49",
          success: "#4ade80",
          "success-content": "#052e16",
          warning: "#facc15",
          "warning-content": "#422006",
          error: "#f87171",
          "error-content": "#450a0a",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.375rem",
          "--rounded-badge": "999px",
          "--animation-btn": "0.16s",
          "--animation-input": "0.16s",
          "--btn-focus-scale": "0.98",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.375rem",
        },
      },
      "winter",
      "business",
      "retro",
      "night",
      "dracula"
    ],
    darkTheme: "hcoco-dark",
    logs: false,
  },
};
